version: '3'
services:
  front-end:
    build: front-end/
    container_name: jordan_front_end
    working_dir: /app
    volumes: 
      - ./front-end:/app
    stdin_open: true
    tty: true
    command: sh
    ports: 
      - 3000:3000
    restart: on-failure

  data-base:
    image: mysql:8.0
    container_name: jordan_data_base
    volumes:
      - ./data-base:/var/lib/mysql
    ports:
      - 33060:3306
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=password


